// export const SAVE_IMAGES = 'save_images'
export const SAVE_INDEX = 'save_index'
export const SAVE_GETCATENAVDATAS = 'save_getcateNavDatas'
export const SAVE_GETCATELISTS = 'save_getcateLists'
export const SAVE_GETWATERFALL = 'save_getwaterFall'
export const SAVE_GETLANJIAZAI = 'save_getlanjiazai'